def unitNames():

    names = {
        'unsc_inf_flameMarine_01' : 'FLAMER' ,
        "cov_veh_corruptedscarab_01" : "VOLATILE SCARAB" ,
        "cov_inf_rm_corruptedwarlord_01" : "VORIDUS" ,
        "cov_inf_corruptedwarlord_01" : "VORIDUS" ,
        "cov_inf_rm_mortarwarlord_01" : "PAVIUM" ,
        "cov_inf_mortarwarlord_01" : "PAVIUM" ,
        "cov_inf_rm_gruntswarm_01" : "CANNON FODDER" ,
        "cov_inf_gruntswarm_01_frommine" : "CANNON FODDER" ,
        "unsc_air_rm_pegasus_01" : "FROSTRAVEN" ,
        "unsc_air_serina_pegasus_01" : "FROSTRAVEN" ,
        "unsc_inf_rm_serina_cryomarines_01" : "CRYO TROOPERS" ,
        "unsc_inf_serina_cryomarines_01" : "CRYO TROOPERS" ,
        "unsc_veh_serina_hero_01" : "BISON" ,
        "unsc_veh_rm_serina_hero_01" : "BISON" ,
        "unsc_veh_johnson_colossus_01" : "COLOSSUS" ,
        "unsc_veh_rm_colossus_01" : "COLOSSUS" ,
        "cpgnh_veh_m02colossus_01" : "COLOSSUS" ,
        "unsc_inf_johnson_hero_01" : "SGT. JOHNSON" ,
        "cov_inf_arbiter_01" : "THE ARBITER" ,
        "cov_inf_rm_arbiter_01" : "THE ARBITER" ,
        "cov_inf_generic_arbitergruntsquad" : "GRUNTS" ,
        "cov_inf_arbiter_gruntsquad_02" : "GRUNTS" ,
        "cov_inf_arbiter_gruntsquad_01" : "GRUNTS" ,
        "cov_inf_rm_grunt_04" : "GRUNTS" ,
        "cov_inf_generic_arbiterenforcer" : "ELITE ENFORCERS" ,
        "cov_inf_arbiter_assaultteam_01" : "ELITE ENFORCERS" ,
        "cov_inf_arbiter_assaultteam_02" : "ELITE ENFORCERS" ,
        "cov_inf_rm_eliteassaultteam_01" : "ELITE ENFORCERS" ,
        "cov_air_rm_phantom_01" : "PHANTOM" ,
        "cov_air_phantom_01" : "PHANTOM" ,
        "unsc_veh_rm_battleapc_01" : "MASTODON" ,
        "unsc_veh_battleapc_01" : "MASTODON" ,
        "unsc_inf_rm_omegateam_robert_01" : "ROBERT-025" ,
        "unsc_inf_omegateam_robert_01" : "ROBERT-025" ,
        "unsc_inf_rm_omegateam_leon_01" : "LEON-011" ,
        "unsc_inf_omegateam_leon_01" : "LEON-011" ,
        "unsc_inf_omegateam_august_01" : "AUGUST-099" ,
        "unsc_inf_rm_omegateam_august_01" : "AUGUST-099" ,
        "cov_inf_lekgologoliath_01" : "GOLIATH" ,
        "cov_inf_rm_goliath_01" : "GOLIATH" ,
        "cov_veh_rm_skitterer_01" : "SKITTERER" ,
        "cov_veh_skitterer_01" : "SKITTERER" ,
        "cov_inf_impervioushunterm02_01" : "HUNTER CAPTAIN" ,
        "cov_inf_rm_impervioushunter_01" : "HUNTER CAPTAIN" ,
        "cov_inf_impervioushunter_01" : "HUNTER CAPTAIN" ,
        "unsc_veh_rm_grenadehog_01" : "FLAME WARTHOG" ,
        "unsc_veh_rm_flamehog_01" : "FLAME WARTHOG" ,
        "unsc_veh_flamehog_01" : "FLAME WARTHOG" ,
        "flood_bldg_egg_02" : "BLISTER" ,
        "cov_bldg_barricade_barrier_01" : "SHIELD BARRIER" ,
        "flood_bldg_egg_01" : "BLISTER" ,
        "flood_bldg_infectedbanbase_01" : "COCOONED BASE" ,
        "cov_veh_rm_wraithapc_01" : "WRAITH INVADER" ,
        "cov_inf_rm_corruptedengineer_01" : "INFUSED ENGINEER" ,
        "flood_inf_infectfrm_01" : "POD INFECTOR" ,
        "cov_inf_generic_brutejumppack_fromlich" : "JUMP PACK BRUTES" ,
        "cov_veh_locust_01_fromlich" : "LOCUST" ,
        "cov_veh_rm_wraith_03" : "WRAITH" ,
        "cov_veh_wraithapc_01_fromlich" : "WRAITH INVADER" ,
        "flood_air_airborneinfector_01" : "SEEDER INFECTORS" ,
        "cov_bldg_corruptbomb_01" : "DROP TURRET" ,
        "cov_bldg_minibase3sockfirefight_01" : "THREE-SLOT MINIBASE" ,
        "cov_bldg_grunt_shadeturret_01" : "SHADE TURRET" ,
        "episode2_maps_m03_drillpole" : "SALVAGE DRILLS" ,
        "unsc_bldg_barricade_wall_01" : "FENCE" ,
        "flood_bldg_rupture_01" : "BURSTER" ,
        "flood_inf_vehinfector_01" : "INFESTER" ,
        "cov_veh_gorgon_01_fromlich" : "REAVER" ,
        "cov_inf_generic_brutegrenadier_fromlich" : "BRUTE GRENADIERS" ,
        "cov_bldg_unbreakablemegaturret_01" : "MEGA TURRET" ,
        "cov_bldg_emptower_01" : "DISRUPTION EMITTER" ,
        "for_building_turret_01" : "FORERUNNER TURRET" ,
        "cov_inf_generic_suicidegrunt_fromlich" : "SUICIDE GRUNTS" ,
        "cov_inf_engineer_01_ff" : "ENGINEER" ,
        "cov_inf_corruptedengineer_01" : "INFUSED ENGINEER" ,
        "unsc_bldg_minibase3sockfirefight_01" : "THREE-SLOT MINIBASE" ,
        "cov_veh_brutechopper_01_fromlich" : "CHOPPER" ,
        "hook_bldg_minibase3sockfirefight_01" : "MINIBASE SITE" ,
        "cov_bldg_corruptbomb_02" : "DROP TURRET" ,
        "unsc_bldg_barricade_electric_01" : "ELECTRIC TRAP" ,
        "cov_bldg_barricade_caltrops_01" : "FLOOR BLADES" ,
        "cov_veh_shortrangelocust_01" : "LOCUST" ,
        "cov_inf_rm_brutegrenadier_01" : "BRUTE GRENADIERS" ,
        "flood_inf_commander_01" : "ABOMINATION" ,
        "cov_inf_generic_grunt_fromlich" : "GRUNT SQUAD" ,
        "neutralfor_sentineltier2_02" : "PROTECTOR SENTINEL" ,
        "cov_air_rm_blisterback_03" : "BLISTERBACK" ,
        "cov_inf_brutejumppack_02_ep2" : "JUMP PACK BRUTES" ,
        "cov_veh_wraithapc_01" : "WRAITH INVADER" ,
        "cov_inf_jackal_01_fromlich" : "ELITE RANGERS" ,
        "cov_inf_brutegrenadier_01" : "BRUTE GRENADIERS" ,
        "unsc_bldg_barricade_minefield_01" : "LOTUS MINEFIELD" ,
        "cov_inf_hunter_01_fromlich" : "HUNTERS" ,
        "flood_inf_spawner_01" : "SPAWNER" ,
        "flood_bldg_hive_01" : "SPORE MOUND" ,
        "neutralfor_sentineltier2_01" : "PROTECTOR SENTINEL" ,
        "cov_inf_gruntgoblin01" : "GRUNT GOBLIN" ,
        "cov_veh_wraith_01_fromlich" : "WRAITH" ,
        "cov_bldg_barricade_barrels_01" : "UNSTABLE BARRELS" ,
        "neutralfor_sentineltier2_generic" : "PROTECTOR SENTINEL" ,
        "unsc_veh_rm_forgehog_01" : "FORGE'S WARTHOG" ,
        "cov_bldg_megaturret_01" : "MEGA TURRET" ,
        "cov_inf_bruterider_01" : "GRUNT RIDERS" ,
        "cov_veh_prowler_01_fromlich" : "MARAUDER" ,
        "neutralfor_rm_sentineltier2_02" : "PROTECTOR SENTINEL" ,
        "neutralfor_rm_sentineltier2_01" : "PROTECTOR SENTINEL" ,
        "unsc_veh_forgehog_01" : "FORGE'S WARTHOG" ,
        "cov_inf_rm_gruntgoblin01" : "GRUNT GOBLIN" ,
        "cov_inf_rm_bruterider_01" : "GRUNT RIDERS" ,
        "unsc_bldg_turretav_01" : "ANTI-VEHICLE TURRET" ,
        "cov_bldg_reactor_02" : "AUG. EXTRACTOR" ,
        "cov_bldg_builder_02" : "STRONGHOLD" ,
        "cov_bldg_rm_dropturret_01" : "SPIKE TURRET" ,
        "unsc_bldg_command_02" : "COMBAT STATION" ,
        "unsc_bldg_johnsonbunker_01" : "BUNKER" ,
        "unsc_bldg_command_04" : "HEADQUARTERS" ,
        "unsc_bldg_command_03" : "COMMAND CENTER" ,
        "unsc_bldg_reactor_02" : "ADV. GENERATOR" ,
        "unsc_bldg_turretai_01" : "ANTI-INFANTRY TURRET" ,
        "cov_bldg_builder_04" : "FORTRESS" ,
        "unsc_bldg_turretaa_01" : "ANTI-AIR TURRET" ,
        "cov_bldg_supplydepot_02" : "AUG. HARVESTER" ,
        "cov_bldg_builder_03" : "CITADEL" ,
        "unsc_bldg_supplypad_02" : "HEAVY SUPPLY PAD" ,
        "cov_veh_grunt_methanewagon_01" : "METHANE WAGON" ,
        "cov_bldg_rm_grunt_shieldtower_01" : "GRUNTDOME" ,
        "cov_inf_heavygrunt_02" : "HEAVY GRUNTS" ,
        "cov_bldg_grunt_shieldtower_01" : "GRUNTDOME" ,
        "cov_inf_generic_heavygrunt" : "HEAVY GRUNTS" ,
        "cov_veh_grunt_prowler_01" : "MARAUDER" ,
        "cov_veh_grunt_brutechopper_01" : "CHOPPER" ,
        "cov_inf_heavygrunt_01" : "HEAVY GRUNTS" ,
        "cov_bldg_grunt_shieldtower_02" : "GRUNTDOME" ,
        "cov_inf_gruntswarm_01" : "CANNON FODDER" ,
        "cov_veh_rm_grunt_methanewagon_01" : "METHANE WAGON" ,
        "cov_inf_rm_heavygrunt_01" : "HEAVY GRUNTS" ,
        "cov_inf_rm_brutejumppack_02" : "JUMP PACK BRUTES" ,
        "for_air_enforcer_shielded_01" : "CONTROLLER SENTINEL" ,
        "for_air_enforcer_01" : "CONTROLLER SENTINEL" ,
        "for_air_enforcer_m02_fullshield" : "CONTROLLER SENTINEL" ,
        "unsc_bldg_serina_iceblock_01" : "ICE BARRIER" ,
        "unsc_bldg_colossus_pad_01" : "COLOSSUS PAD" ,
        "unsc_bldg_rm_serina_iceblock_01" : "ICE BARRIER" ,
        "unsc_bldg_rm_serina_iceblock_02" : "ICE BARRIER" ,
        "unsc_inf_rm_spartan_chaingun_01" : "ALICE-130" ,
        "unsc_inf_spartan_chaingun_01" : "ALICE-130" ,
        "unsc_inf_mp_spartan_01" : "JEROME-092" ,
        "unsc_inf_rm_spartan_laser_01" : "JEROME-092" ,
        "unsc_inf_rm_flamecyclops_01" : "KINSANO'S CYCLOPS" ,
        "unsc_inf_rm_omegateam_jerome_01" : "COMMANDER JEROME" ,
        "unsc_inf_rm_spartan_rocket_01" : "DOUGLAS-042" ,
        "unsc_inf_spartan_mpalice_01" : "ALICE-130" ,
        "unsc_inf_rm_johnsonhero_01" : "SGT. JOHNSON" ,
        "unsc_inf_omegateam_jerome_01" : "COMMANDER JEROME" ,
        "unsc_veh_jerome_mantis_01" : "COMMAND MANTIS" ,
        "unsc_inf_spartan_mpdoug_01" : "DOUGLAS-042" ,
        "unsc_inf_spartan_laser_01" : "JEROME-092" ,
        "unsc_inf_spartan_mpjerome_01" : "JEROME-092" ,
        "unsc_inf_spartan_rocket_01" : "DOUGLAS-042" ,
        "unsc_inf_flamecyclops_01" : "KINSANO'S CYCLOPS" ,
        "unsc_inf_rm_sniper_02" : "SNIPER" ,
        "unsc_air_rm_nightingale_02" : "NIGHTINGALE" ,
        "unsc_bldg_victoryturret_01" : "VICTORY TURRET" ,
        "unsc_veh_rm_jerome_mantis_01" : "COMMAND MANTIS" ,
        "unsc_bldg_rm_victoryturret_01" : "VICTORY TURRET" ,
        "cov_bldg_dropturret_01_sp" : "DROP TURRET" ,
        "cov_bldg_dropturret_01_base" : "DROP TURRET" ,
        "unsc_veh_rm_mantis_02" : "MANTIS" ,
        "cov_bldg_lekgolo_buffmine_01" : "DROP TURRET" ,
        "cov_bldg_dropturret_01" : "DROP TURRET" ,
        "unsc_bldg_rm_watchtower_01" : "DROP TURRET" ,
        "cov_bldg_dropturret_01_mp" : "DROP TURRET" ,
        "unsc_veh_johnson_mantis_01" : "MANTIS" ,
        "unsc_veh_rm_mantis_01" : "MANTIS" ,
        "unsc_inf_rm_sniper_01" : "SNIPER" ,
        "unsc_inf_flamemarine_01" : "HELLBRINGERS" ,
        "cov_veh_rm_locust_03" : "LOCUST" ,
        "unsc_bldg_minibase3sock_01" : "STRONGHOLD" ,
        "cov_veh_prowler_01" : "MARAUDER" ,
        "cov_veh_scarab_01" : "SCARAB" ,
        "unsc_veh_scorpion_01" : "SCORPION" ,
        "cov_inf_generic_grunt" : "GRUNT SQUAD" ,
        "cov_inf_rm_hunter_03" : "HUNTERS" ,
        "unsc_veh_warthog_01" : "WARTHOG" ,
        "unsc_bldg_command_01" : "FIREBASE" ,
        "cov_bldg_reactor_01" : "POWER EXTRACTOR" ,
        "cov_air_blisterback_01" : "BLISTERBACK" ,
        "cov_inf_engineer_01" : "ENGINEER" ,
        "cov_bldg_turret_01" : "TURRET" ,
        "unsc_bldg_airpad_01" : "AIRPAD" ,
        "cov_air_banshee_01" : "BANSHEE" ,
        "unsc_air_vulture_01" : "VULTURE" ,
        "unsc_bldg_vehicledepot_01" : "GARAGE" ,
        "cov_bldg_watchtower_01" : "SENSOR TOWER" ,
        "cov_bldg_supplydepot_01" : "HARVESTER" ,
        "cov_bldg_minibase3sock_01" : "STRONGHOLD" ,
        "cov_veh_gorgon_01" : "REAVER" ,
        "cov_inf_elitecommando_01" : "HONOR GUARD" ,
        "unsc_inf_sniper_01" : "SNIPER" ,
        "unsc_air_destroyer_01" : "CONDOR GUNSHIP" ,
        "cov_bldg_minibase2sock_01" : "TWO-SLOT MINIBASE" ,
        "cov_inf_atrioxchosen_01" : "ATRIOX'S CHOSEN" ,
        "cov_air_shroud_01" : "SHROUD" ,
        "cov_veh_wraith_01" : "WRAITH" ,
        "cov_inf_hunter_01" : "HUNTERS" ,
        "cov_inf_brutejumppack_01" : "JUMP PACK BRUTES" ,
        "unsc_bldg_dropturret_01" : "DROP TURRET" ,
        "cov_veh_ghost_01" : "GHOST" ,
        "cov_bldg_temple_01" : "WAR COUNCIL" ,
        "cov_inf_brutehonour_01" : "WARLORD" ,
        "cov_veh_brutechopper_01" : "CHOPPER" ,
        "unsc_veh_wolverine_01" : "WOLVERINE" ,
        "cov_veh_locust_01" : "LOCUST" ,
        "unsc_inf_generic_marine" : "MARINES" ,
        "unsc_veh_rm_grizzly_01" : "GRIZZLY" ,
        "cov_inf_mpdecimus_01" : "DECIMUS" ,
        "unsc_bldg_supplypad_01" : "SUPPLY PAD" ,
        "unsc_bldg_fieldarmory_01" : "ARMORY" ,
        "cov_bldg_minibase1sock_01" : "ONE-SLOT MINIBASE" ,
        "cov_bldg_builder_01" : "OUTPOST" ,
        "unsc_bldg_minibase2sock_01" : "TWO-SLOT MINIBASE" ,
        "unsc_air_hornet_01" : "HORNET" ,
        "cov_inf_generic_brutejumppack" : "JUMP PACK BRUTES" ,
        "cov_bldg_shieldtower_01" : "SHIELD GENERATOR" ,
        "unsc_air_nightingale_01" : "NIGHTINGALE" ,
        "unsc_bldg_minibase1sock_01" : "ONE-SLOT MINIBASE" ,
        "unsc_inf_cyclops_01" : "CYCLOPS" ,
        "cov_bldg_barracks_01" : "RAID CAMP" ,
        "unsc_bldg_siegegun_01" : "SIEGE TURRET" ,
        "unsc_veh_mongoose_01" : "JACKRABBIT" ,
        "cov_inf_jackal_01" : "ELITE RANGERS" ,
        "cov_bldg_cloaktower_01" : "CLOAKING GENERATOR" ,
        "unsc_veh_grizzly_01" : "GRIZZLY" ,
        "unsc_bldg_reactor_01" : "GENERATOR" ,
        "unsc_bldg_turret_01" : "TURRET" ,
        "unsc_inf_odst_01" : "ODSTs" ,
        "cov_inf_generic_suicidegrunt" : "SUICIDE GRUNTS" ,
        "unsc_veh_foxcannon_01" : "KODIAK" ,
        "unsc_bldg_barracks_01" : "BARRACKS" ,
        "cov_bldg_lightfactory_01" : "APEX" ,
        "unsc_bldg_watchtower_01" : "WATCHTOWER" ,
        "unsc_inf_rm_flamemarine_03" : "HELLBRINGERS" ,
        "unsc_inf_rm_flamemarine_04" : "HELLBRINGERS" ,
        "unsc_veh_rm_mongoose_03" : "JACKRABBIT" ,
        "unsc_veh_rm_mongoose_01" : "JACKRABBIT" ,
        "cov_veh_rm_ghost_01" : "GHOST" ,
        "cov_veh_rm_brutechopper_01" : "CHOPPER" ,
        "cov_air_rm_banshee_02" : "BANSHEE" ,
        "unsc_veh_rm_mongoose_02" : "JACKRABBIT" ,
        "unsc_veh_rm_warthog_02" : "WARTHOG" ,
        "cov_veh_rm_brutechopper_02" : "CHOPPER" ,
        "cpgnh_p01_warthogspartan_01" : "SPARTAN WARTHOG" ,
        "unsc_bldg_minibasenosocks" : "MINIBASE" ,
        "unsc_inf_rm_cyclops_01" : "CYCLOPS" ,
        "cov_inf_rm_hunter_01" : "HUNTERS" ,
        "cov_air_rm_blisterback_02" : "BLISTERBACK" ,
        "unsc_veh_rm_wolverine_01" : "WOLVERINE" ,
        "cpgnh_p01_warthogspartan_02" : "SPARTAN WARTHOG" ,
        "cov_inf_rm_brutehonour_01" : "WARLORD" ,
        "cov_inf_rm_grunt_01" : "GRUNT SQUAD" ,
        "cov_inf_rm_engineer_01" : "ENGINEER" ,
        "unsc_inf_rm_marine_01" : "MARINES" ,
        "unsc_air_rm_wingmenhornet_01" : "HORNET" ,
        "unsc_air_rm_nightingale_01" : "NIGHTINGALE" ,
        "cov_veh_rm_wraith_01" : "WRAITH" ,
        "unsc_inf_rm_flamemarine_02" : "HELLBRINGERS" ,
        "unsc_inf_rm_flamemarine_01" : "HELLBRINGERS" ,
        "unsc_air_rm_hornet_01" : "HORNET" ,
        "cov_veh_rm_wraith_02" : "WRAITH" ,
        "unsc_veh_rm_scorpion_01" : "SCORPION" ,
        "cov_inf_rm_elitecommando_01" : "HONOR GUARD" ,
        "unsc_veh_rm_foxcannon_02" : "KODIAK" ,
        "cov_veh_rm_locust_01" : "LOCUST" ,
        "unsc_inf_rm_odst_01" : "ODSTs" ,
        "unsc_veh_rm_warthog_01" : "WARTHOG" ,
        "unsc_veh_rm_foxcannon_01" : "KODIAK" ,
        "unsc_veh_rm_scorpion_02" : "SCORPION" ,
        "cov_inf_rm_brutejumppack_01" : "JUMP PACK BRUTES" ,
        "unsc_air_rm_vulture_01" : "VULTURE" ,
        "neutralfor_rm_sentinel_01" : "SENTINEL" ,
        "cov_veh_rm_prowler_01" : "MARAUDER" ,
        "cov_inf_rm_grunt_02" : "GRUNT SQUAD" ,
        "cov_inf_rm_atrioxchosen_01" : "ATRIOX'S CHOSEN" ,
        "unsc_inf_rm_marinereflect_01" : "MARINES" ,
        "cov_inf_rm_hunter_02" : "HUNTERS" ,
        "cov_air_rm_banshee_01" : "BANSHEE" ,
        "unsc_inf_rm_cyclops_02" : "CYCLOPS" ,
        "cov_veh_rm_prowler_03" : "MARAUDER" ,
        "unsc_veh_rm_gausswarthog_01" : "WARTHOG" ,
        "cov_veh_rm_locust_02" : "LOCUST" ,
        "cov_inf_suicidegrunt_02_sp" : "SUICIDE GRUNTS" ,
        "unsc_inf_flamemarine_02_sp" : "HELLBRINGERS" ,
        "cpgnh_veh_emptyhog_01" : "WARTHOG" ,
        "for_air_sentinel_01" : "AGGRESSOR SENTINEL" ,
        "unsc_inf_flamemarine_02" : "HELLBRINGERS" ,
        "cov_inf_rm_decimus_01" : "DECIMUS" ,
        "cov_inf_suicidegrunt_02_mp" : "SUICIDE GRUNTS" ,
        "cov_bldg_heavyfactory_01" : "FOUNDRY" ,
        "cov_veh_rm_prowler_02" : "MARAUDER" ,
        "unsc_inf_training_marine" : "MARINES" ,
        "cpgnh_odstsm06_01" : "ODSTs" ,
        "unsc_inf_flamemarine_02_base" : "HELLBRINGERS" ,
        "unsc_inf_rm_cyclops_03" : "CYCLOPS" ,
        "unsc_veh_rm_wolverine_02" : "WOLVERINE" ,
        "unsc_inf_generic_marinetutorial_01" : "MARINES" ,
        "cov_inf_brutejumppack_02_sp" : "JUMP PACK BRUTES" ,
        "cov_inf_rm_suicidegrunt_01" : "SUICIDE GRUNTS" ,
        "cov_inf_grunt_01" : "GRUNT SQUAD" ,
        "unsc_inf_mpmarine_01" : "MARINES" ,
        "unsc_inf_flamemarine_02_mp" : "HELLBRINGERS" ,
        "cpgnh_rangersm06_01" : "ELITE RANGERS" ,
        "unsc_inf_gen_marine_02" : "MARINES" ,
        "cov_inf_suicidegrunt_02" : "SUICIDE GRUNTS" ,
        "unsc_air_rm_destroyer_01" : "CONDOR GUNSHIP" ,
        "cov_inf_brutejumppack_02_base" : "JUMP PACK BRUTES" ,
        "cov_air_rm_blisterback_01" : "BLISTERBACK" ,
        "cov_veh_rm_gorgon_01" : "REAVER" ,
        "cov_inf_suicidegrunt_02_base" : "SUICIDE GRUNTS" ,
        "unsc_inf_gen_marine_01" : "MARINES" ,
        "unsc_inf_rm_marinesiphon_01" : "MARINES" ,
        "cov_inf_grunt_02_base" : "GRUNT SQUAD" ,
        "unsc_inf_marine_02" : "MARINES" ,
        "unsc_inf_rm_marineguard_01" : "MARINES" ,
        "unsc_inf_marine_01" : "MARINES" ,
        "cov_inf_suicidegrunt_01" : "SUICIDE GRUNTS" ,
        "cov_inf_rm_jackal_02" : "ELITE RANGERS" ,
        "for_air_sentineltier2_01" : "PROTECTOR SENTINEL" ,
        "cov_inf_rm_jackal_01" : "ELITE RANGERS" ,
        "cov_bldg_minibasenosocks" : "MINIBASE" ,
        "unsc_veh_rm_foxcannonrush_01" : "KODIAK" ,
        "cov_inf_grunt_02_mp" : "GRUNT SQUAD" ,
        "cov_inf_grunt_02_sp" : "GRUNT SQUAD" ,
        "cov_inf_brutejumppack_02_mp" : "JUMP PACK BRUTES" ,
        "cov_inf_brutejumppack_02" : "JUMP PACK BRUTES" ,
        "cov_inf_rm_grunt_03" : "GRUNT SQUAD" ,
        "unsc_inf_spmarine_02" : "MARINES" ,
        "unsc_inf_spmarine_01" : "MARINES" ,
        "cov_bldg_supplydepot_03" : "SUPER HARVESTER" ,
        "cov_veh_rm_gorgon_02" : "REAVER" ,
        "cov_veh_rm_scarab_01" : "SCARAB" ,
        "cpgnh_rangersindividualm06_01" : "ELITE RANGERS" ,
        "unsc_inf_mpmarine_02" : "MARINES" ,
        "cov_inf_grunt_02" : "GRUNT SQUAD" ,
        "neutralfor_sentinel_01" : "SENTINEL" ,
        "cpgnh_sniperm06_01" : "SNIPER" ,
        "hook_bldg_dominationpoints_dominationpointc" : "CONTROL TOWER C" ,
        "hook_bldg_dominationpoints_dominationpointb" : "CONTROL TOWER B" ,
        "cpgnh_anders_01" : "ANDERS" ,
        "hook_bldg_warehouse_power01" : "POWER SILO" ,
        "cpgn_inf_spartanrocket_01" : "JEROME-092" ,
        "cov_bldg_socket_01" : "Banished Build Site" ,
        "cov_inf_specopselite_01" : "INFILTRATOR" ,
        "unsc_bldg_antiinfantryturret_01" : "ANTI-INFANTRY TURRET" ,
        "sys_marker_rally_01" : "GLOBAL RALLY POINT" ,
        "hook_bldg_teleporter_teleporterblue01" : "TELEPORTER" ,
        "unsc_inf_sp_spartan_01" : "JEROME-092" ,
        "unsc_inf_operative_01" : "ONI OPERATIVE" ,
        "cov_bldg_reactor_03" : "SUPER EXTRACTOR" ,
        "cpgn_inf_spartansharpshooter_01" : "JEROME-092" ,
        "hook_bldg_dominationpoints_dominationpointa" : "CONTROL TOWER A" ,
        "hook_bldg_dominationpoints_dominationpointd" : "CONTROL TOWER D" ,
        "hook_bldg_dominationpoints_dominationpointe" : "CONTROL TOWER E" ,
        "archetypes_forerunner_pieces_forerunnermagcannon" : "PARTICLE CANNON" ,
        "unsc_inf_spartan_01" : "JEROME-092" ,
        "cov_bldg_turretsocket_01" : "TURRET SITE" ,
        "unsc_bldg_turretsocket_01" : "TURRET SITE" ,
        "rostermode_hook_capturepointA" : "rostermode_hook_capturepointA" ,
        "rostermode_hook_capturepointB" : "rostermode_hook_capturepointB" ,
        "rostermode_hook_capturepointC" : "rostermode_hook_capturepointC" ,
        "unsc_bldg_antiairturret_01" : "ANTI-AIR TURRET" ,
        "unsc_bldg_antivehicleturret_01" : "ANTI-VEHICLE TURRET" ,
        "cpgn_inf_spartanmg_01" : "ALICE-130" ,
        "unsc_air_condor_01" : "CONDOR GUNSHIP" ,
        "sys_marker_rally_cov" : "GLOBAL RALLY POINT" ,
        "hook_bldg_warehouse_supplies01" : "BANISHED SUPPLY SILO" ,
        "cpgn_inf_spartansniper_01" : "JEROME-092" ,
        "for_air_retriever_base" : "RETRIEVER SENTINEL" ,
        "unsc_bldg_socket_01" : "BUILDING MENU" ,
    }
    
    return names
